service: anibot
 
provider: # Required to tell serverless this is an aws project, modify as needed
  name: aws
  runtime: python3.8
  # Modify the following with real aws profile to deploy to aws
  # Add more attributes as needed to suit your aws environment, eg. region
  stage: prod
  profile: botprofile
  logRetentionInDays: 14
  environment:
    ANIBOT_TOKEN: ${env:ANIBOT_TOKEN}

# Configure your lambda function(s) here
functions:
  bot:
    maximumRetryAttempts: 0
    handler: bot.handler
    events:
      - http:
          path: /bot
          method: post
          async: true
  
  auth:
    maximumRetryAttempts: 0
    handler: auth.handler
    events:
      - http:
          path: /auth
          method: get
          async: true

package:
  exclude:
    - ./node_modules
    - ./local.py
    - setWebhook

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    slim: true
    pythonBin: python3
